spring.application.name=E-ComSync

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.authentication=DEBUG
logging.level.org.springframework.security.web.authentication=DEBUG
# Server config
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ecomsync
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Schema Configuration
  spring.jpa.properties.hibernate.default_schema=product_service

# JWT Configuration
ecomsync.app.jwtSecret=QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiop1234567890
ecomsync.app.jwtExpirationMs=86400000

# OpenAI Configuration (for chatbot)
openai.api.key=${OPENAI_API_KEY}
openai.model=gpt-4o-mini

# Logging Configuration
logging.level.org.springframework=INFO
logging.level.com.ecomsync=DEBUG

# UTF-8
spring.datasource.hikari.connection-init-sql=SET NAMES 'UTF8'

# Allow circular references
spring.main.allow-circular-references=true



